// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function Index$DebouncedSlider(Props) {
  var min = Props.min;
  var max = Props.max;
  var step = Props.step;
  var label = Props.label;
  var value = Props.value;
  var onChange = Props.onChange;
  var timeoutRef = React.useRef(undefined);
  var changeValue = function (e) {
    var match = timeoutRef.current;
    if (match !== undefined) {
      return /* () */0;
    } else {
      var value = String(e.target.value);
      var timeoutId = setTimeout((function (param) {
              timeoutRef.current = undefined;
              return Curry._1(onChange, value);
            }), 10);
      timeoutRef.current = Caml_option.some(timeoutId);
      return /* () */0;
    }
  };
  return React.createElement("div", undefined, React.createElement("input", {
                  max: max,
                  min: min,
                  step: step,
                  type: "range",
                  value: value,
                  onChange: changeValue
                }), React.createElement("label", undefined, label + (" " + value)));
}

var DebouncedSlider = /* module */[/* make */Index$DebouncedSlider];

var $$window = window;

var $$Document = /* module */[/* window */$$window];

var Canvas = /* module */[];

function getNthPoint(width, height, radius, modulo, n) {
  var n_float = n;
  var modulo_float = modulo;
  var centerX = width / 2;
  var centerY = height / 2;
  var pi = Math.PI;
  var dx = radius * Math.cos(2 * pi * n_float / modulo_float);
  var dy = radius * Math.sin(2 * pi * n_float / modulo_float);
  return /* tuple */[
          centerX + dx,
          centerY + dy
        ];
}

function drawOnCanvas(ctx, modulo, multiplier, width, height) {
  var width_float = width;
  var height_float = height;
  var radius = 0.5 * Math.min(width_float * 0.75, height_float * 0.75);
  ctx.clearRect(0, 0, width_float, height_float);
  ctx.beginPath();
  for(var ii = 0 ,ii_finish = modulo - 1 | 0; ii <= ii_finish; ++ii){
    var match = getNthPoint(width_float, height_float, radius, modulo, ii);
    var to_index = Caml_int32.mod_(ii * multiplier | 0, modulo);
    var match$1 = getNthPoint(width_float, height_float, radius, modulo, to_index);
    ctx.moveTo(match[0], match[1]);
    ctx.lineTo(match$1[0], match$1[1]);
  }
  ctx.stroke();
  ctx.closePath();
  return /* () */0;
}

function Index$ModuloTimesTable(Props) {
  var modulo = Props.modulo;
  var multiplier = Props.multiplier;
  var width = Props.width;
  var height = Props.height;
  var canvasRef = React.useRef(null);
  React.useEffect((function (param) {
          var canvas = canvasRef.current;
          if (!(canvas == null)) {
            canvas.width = width;
            canvas.height = height;
            var ctx = canvas.getContext("2d");
            drawOnCanvas(ctx, modulo, multiplier, width, height);
          }
          return undefined;
        }), /* tuple */[
        modulo,
        multiplier,
        width,
        height
      ]);
  return React.createElement("canvas", {
              ref: canvasRef
            }, "Canvas not supported!?");
}

var ModuloTimesTable = /* module */[/* make */Index$ModuloTimesTable];

function getWindowSize(param) {
  return /* tuple */[
          $$window.innerWidth,
          $$window.innerHeight
        ];
}

function Index$App(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var setFrameId = match[1];
  var frameId = match[0];
  var match$1 = React.useState((function () {
          return getWindowSize(/* () */0);
        }));
  var setSize = match$1[1];
  var match$2 = match$1[0];
  var match$3 = React.useState((function () {
          return 571;
        }));
  var setModulo = match$3[1];
  var modulo = match$3[0];
  var match$4 = React.useState((function () {
          return 2;
        }));
  var setMultiplier = match$4[1];
  var multiplier = match$4[0];
  React.useEffect((function () {
          var updateSize = function (param) {
            return Curry._1(setSize, (function (param) {
                          return getWindowSize(/* () */0);
                        }));
          };
          $$window.addEventListener("resize", updateSize);
          return (function (param) {
                    $$window.removeEventListener("resize", updateSize);
                    return /* () */0;
                  });
        }));
  React.useEffect((function () {
          if (frameId === undefined) {
            var animationFrameId = requestAnimationFrame((function (param) {
                    Curry._1(setMultiplier, (function (mult) {
                            var match = mult >= 20;
                            if (match) {
                              return 2;
                            } else {
                              return mult + 0.01;
                            }
                          }));
                    return Curry._1(setFrameId, (function (param) {
                                  return undefined;
                                }));
                  }));
            Curry._1(setFrameId, (function (param) {
                    return Caml_option.some(animationFrameId);
                  }));
          }
          return undefined;
        }));
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "controls"
                }, React.createElement(Index$DebouncedSlider, {
                      min: 3,
                      max: "600",
                      step: 1,
                      label: "modulo",
                      value: String(modulo),
                      onChange: (function (newVal) {
                          return Curry._1(setModulo, (function (param) {
                                        return Caml_format.caml_int_of_string(newVal);
                                      }));
                        })
                    }), React.createElement(Index$DebouncedSlider, {
                      min: 2,
                      max: (20).toString(),
                      step: 0.01,
                      label: "multiplier",
                      value: multiplier.toFixed(3),
                      onChange: (function (newVal) {
                          return Curry._1(setMultiplier, (function (param) {
                                        return Caml_format.caml_float_of_string(newVal);
                                      }));
                        })
                    })), React.createElement(Index$ModuloTimesTable, {
                  modulo: modulo,
                  multiplier: multiplier,
                  width: match$2[0],
                  height: match$2[1]
                }));
}

var App = /* module */[
  /* getWindowSize */getWindowSize,
  /* multiplierMin */2,
  /* multiplierMax */20,
  /* multiplierStep */0.01,
  /* make */Index$App
];

ReactDOMRe.renderToElementWithId(React.createElement(Index$App, { }), "app");

export {
  DebouncedSlider ,
  $$Document ,
  Canvas ,
  getNthPoint ,
  drawOnCanvas ,
  ModuloTimesTable ,
  App ,
  
}
/* window Not a pure module */
